apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: resultserver-service
  name: resultserver-service
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30002
  selector:
    app: resultserver-deploymnt
  type: NodePort
status:
  loadBalancer: {}
