apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: resultserver-deploymnt
  name: resultserver-deploymnt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver-deploymnt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: resultserver-deploymnt
    spec:
      containers:
      - image: mustafabacanak/resultserver:v1
        name: resultserver
        ports:
          - containerPort: 80
        resources: {}
        envFrom :
          - configMapRef:
              name: serverconfig
        env : 
          - name: MYSQL_PASSWORD
            valueFrom: 
              secretKeyRef:
                key: MYSQL_PASSWORD
                name: mysecret
status: {}
